Small illustration fixes, settings adjustment, onboarding exception (#288)
* settings icon tracing resized, missing grey color added

* fixed dark mode / light mode illustrations

* fixed small issue in strings

* OnBoardingTracingFragment: catch exceptions also for asyncIsEnabled() (#282)

Executing `InternalExposureNotificationClient.asyncIsEnabled()` may also result in an exception of `com.google.android.gms.common.api.ApiException` if connection to GMS isn't possible. Not catching this exception results in fatal crash.

```
2020-06-08 16:33:29.693 20904-20904/de.rki.coronawarnapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.rki.coronawarnapp, PID: 20904
    com.google.android.gms.common.api.ApiException: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39507), resolution=null, message=null}
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.3.0:4)
        at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@17.3.0:2)
        at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.3.0:18)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.3.0:211)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.3.0:217)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.3.0:115)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.3.0:79)
        at com.google.android.gms.common.internal.zag.onConnectionFailed(com.google.android.gms:play-services-base@@17.3.0:2)
        at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(com.google.android.gms:play-services-basement@@17.3.0:6)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.3.0:25)
        at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzc(com.google.android.gms:play-services-basement@@17.3.0:11)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(com.google.android.gms:play-services-basement@@17.3.0:49)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at com.google.android.gms.internal.common.zzi.dispatchMessage(com.google.android.gms:play-services-basement@@17.3.0:8)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Co-authored-by: Jakob Möller <jakob.moeller@sap.com>
Co-authored-by: marcmuschko <marc.muschko@sap.com>

* build fixes in tests

Co-authored-by: lenke182 <jan_lenke@freenet.de>
Co-authored-by: Jakob Möller <jakob.moeller@sap.com>